M48
; DRILL file {KiCad 9.0.3} date 2026-04-22T13:54:20-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-22T13:54:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X5.715Y-5.3848
X5.9426Y-5.3848
T2
X5.3133Y-4.6623
X6.3583Y-3.4023
M30
