"""Shared code and constants for firmware modules."""

from common.constants import (
    BOOT_HIGH_IS_CENTRAL,
    BOOT_SELECT_PIN,
    BOOT_SELECT_PULL,
    CENTRAL_ENTRY_MODULE,
    DIFF_ENTRY_MODULE,
    FRAME_SOF,
    MAX_PAYLOAD_SIZE,
    CMD_HEARTBEAT,
    CMD_SET_MODE,
    NODE_ID_CENTRAL,
    NODE_ID_DIFF_FRONT,
    NODE_ID_DIFF_REAR,
    NODE_ID_BROADCAST,
    SERIAL_POLL_DELAY_MS,
    UART_BAUDRATE,
    UART_BITS,
    UART_PARITY,
    UART_STOP,
)
from common.modes import DifferentialMode
from common.switch_input import (
    DiffModeButtons,
    DiffPositionSensors,
    SwitchCollection,
    SwitchInput,
    ThreeInputBank,
    WheelModeButtons,
)

__all__ = [
    "BOOT_HIGH_IS_CENTRAL",
    "BOOT_SELECT_PIN",
    "BOOT_SELECT_PULL",
    "CENTRAL_ENTRY_MODULE",
    "DIFF_ENTRY_MODULE",
    "FRAME_SOF",
    "MAX_PAYLOAD_SIZE",
    "CMD_HEARTBEAT",
    "CMD_SET_MODE",
    "NODE_ID_CENTRAL",
    "NODE_ID_DIFF_FRONT",
    "NODE_ID_DIFF_REAR",
    "NODE_ID_BROADCAST",
    "SERIAL_POLL_DELAY_MS",
    "UART_BAUDRATE",
    "UART_BITS",
    "UART_PARITY",
    "UART_STOP",
    "DifferentialMode",
    "SwitchInput",
    "SwitchCollection",
    "ThreeInputBank",
    "DiffModeButtons",
    "WheelModeButtons",
    "DiffPositionSensors",
]
